# Generated by Django 2.1.7 on 2019-08-16 10:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Name')),
                ('reference', models.CharField(blank=True, max_length=225, verbose_name='Reference')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Blog Post',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Name')),
                ('reference', models.CharField(max_length=225, verbose_name='Reference')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Name')),
                ('reference', models.CharField(blank=True, max_length=225, verbose_name='Reference')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
                ('status', models.BooleanField(default=True)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BlogPost')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Name')),
                ('reference', models.CharField(blank=True, max_length=225, verbose_name='Reference')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Contact Type',
                'verbose_name_plural': 'Contact Types',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rank', models.IntegerField()),
                ('image', models.ImageField(upload_to='header')),
                ('second_image', models.ImageField(blank=True, upload_to='header')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Headers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Name')),
                ('reference', models.CharField(blank=True, max_length=225, verbose_name='Reference')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('content', models.TextField()),
                ('disponibilite', models.CharField(choices=[('Disponible en Stock', 'Disponible en Stock'), ('Plus Disponible', 'Plus Disponible'), ('Stock Limité', 'Stock Limité')], max_length=255)),
                ('image', models.ImageField(upload_to='articles')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
            options={
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_fullname', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
                ('reference', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nesletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Newsletters',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('being_delivered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False, verbose_name='Commandé')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item', verbose_name='Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profil',
                'verbose_name_plural': 'User Profil',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='core.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='type_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ContactType'),
        ),
    ]
