# Generated by Django 2.1.7 on 2019-08-17 09:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_banner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='device',
            field=models.CharField(choices=[('FCFA', 'FCFA'), ('US', 'US')], default='FCFA', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='item',
            name='percentage_reduction',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
