# Generated by Django 2.1.7 on 2019-08-17 10:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190817_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='item',
            name='percentage_reduction',
            field=models.IntegerField(blank=True),
        ),
    ]
